when:
  - event: push
    branch: master

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      repo: kisoft/pdf-merger
      dockerfile: dockerfile
      tag: latest
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_ACCESS_TOKEN